### PR TITLE
Fixes for using react-admin 2.0

### PR DESCRIPTION
**Pull request by Phocea**
Additional changes to use the upcoming version of react-admin
Changes are also needed for material ui 1.0 .. Might need some help on testing UI results

### CODE REVIEW

**Comment by Phocea** [comment]
Travis seems to run on the master and not next branch ... :(
Changes to package.json are therefore probably not needed

**Comment by MhdSyrwan** [comment]
@Phocea  Are you sure? As I can see, the build is based on the PR's head commit.

**Comment by MhdSyrwan** [comment]
Hi @Phocea are you still working on this ? any status update ?

**Comment by MhdSyrwan** [comment]
Implemented in react-admin 2.0.0
Check https://github.com/marmelab/admin-on-rest/pull/697#issuecomment-379074510
And https://github.com/marmelab/admin-on-rest/pull/1717

**Pull request closed without merging**
